version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"

  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=group2db'
      - 'MYSQL_PASSWORD=pbl-2theTop'
#      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'
    volumes:
      - ./resources/db:/docker-entrypoint-initdb.d
